apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: urlog-api
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: urlog-api
subjects:
  - kind: ServiceAccount
    name: urlog-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: urlog-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: urlog-worker
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "pods/log", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: urlog-worker
subjects:
  - kind: ServiceAccount
    name: urlog-worker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: urlog-worker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: urlog-operator
rules:
  - apiGroups: [""]
    resources: ["configmaps", "events", "pods", "services"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: urlog-operator
subjects:
  - kind: ServiceAccount
    name: urlog-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: urlog-operator

