apiVersion: v1
kind: ServiceAccount
metadata:
  name: urlog-api
  labels:
    app.kubernetes.io/name: urlog-api
    app.kubernetes.io/part-of: urlog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: urlog-worker
  labels:
    app.kubernetes.io/name: urlog-worker
    app.kubernetes.io/part-of: urlog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: urlog-operator
  labels:
    app.kubernetes.io/name: urlog-operator
    app.kubernetes.io/part-of: urlog

