apiVersion: v1
kind: Service
metadata:
  name: urlog-api
  labels:
    app.kubernetes.io/name: urlog-api
    app.kubernetes.io/part-of: urlog
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: urlog-api
  ports:
    - name: http
      port: 8080
      targetPort: http

