apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlog-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlog-worker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlog-operator
spec:
  replicas: 0

